## <font color='blue'>Curso de Extensão: Introdução a Linguagem Python para Ciência de Dados - Numpy</font>

In [ ]:
import numpy as np

In [ ]:
#!pip install numpy

In [ ]:
#Cria um numpy array
#x = [10,20,30]
x = numpy.array([10,20,30])
print(x)
y = np.array([40,50,60])
print(y)
#Soma elementos de dois np arrays
print("Soma dos arrays: ",x+y)

[10 20 30]
[40 50 60]
Soma dos arrays:  [50 70 90]


In [ ]:
#Cria np array no formato de matriz
x = np.array([[10,20],[30,40]])
print(x)

[[10 20]
 [30 40]]


In [ ]:
#Soma todos os elementos da matriz
print("Soma todos: ",np.sum(x))
#Soma por coluna, onde axis=0 identifica a coluna
print("Soma por coluna: ", np.sum(x,axis=0))
#Soma por linha, onde axis=1 identifica a linha
print("Soma por linha: ", np.sum(x,axis=1))

Soma todos:  100
Soma por coluna:  [40 60]
Soma por linha:  [30 70]


In [ ]:
#Gera um vetor de números de 5 a 101, intercalando de 5 em 5.
z_arr = np.arange(5,101,5)
print(z_arr)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [ ]:
#Gera um numpy array com números de 0 a 20, com dimensão 5 x 4 (5 linhas e 4 colunas)
y=np.arange(20).reshape(5,4)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [ ]:
#Aplica um reshape em y para gerar 5 arrays no formato 2x2.
#Sintaxe: reshape(quantity of arrays,line,column)
y=y.reshape(5,2,2)
print(y)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [ ]:
print("Shape de y: ", y.shape)
print("Dimensão de y: ", y.ndim)
print("Tamanho de y: ", y.size)
print("Tipo dos dados: ", y.dtype)

Shape de y:  (5, 2, 2)
Dimensão de y:  3
Tamanho de y:  20
Tipo dos dados:  int32


In [ ]:
#Gera um np array 5x5 contedo o valor 0
zeros = np.zeros((5,5)) #zeros
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
#Gera um np array 10x2 contedo o valor 1
ones = np.ones((10,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
#Gera um np array 10x5 contendo o número 3
equals = np.full((10,5),10) #replica
print(equals)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [ ]:
#Gera um np array 6x6 contendo apenas números randômicos
randons = np.around(np.random.random((6,6)),3)
#randons = np.random.random((6,6))
print(randons)

[[0.981 0.54  0.804 0.563 0.164 0.718]
 [0.471 0.3   0.542 0.434 0.566 0.516]
 [0.674 0.395 0.809 0.195 0.958 0.943]
 [0.826 0.73  0.204 0.256 0.759 0.334]
 [0.732 0.511 0.582 0.214 0.353 0.748]
 [0.32  0.114 0.716 0.82  0.276 0.375]]


In [ ]:
#Cria um np array
a = np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
print(a)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [ ]:
#Slice the np array: pega os dados até a linha 3 (excludente) e as colunas de 0 a 2 (excludente)
b=a[0:2,1:3]
print("Array b")
print(b)

Array b
[[20 30]
 [60 70]]


In [ ]:
print("Array a")
print(a[0,1])
b[0,0]=77
print("Array b")
print(b)
print("Array a")
print(a[2,1])

Array a
20
Array b
[[77 30]
 [60 70]]
Array a
100
